"""Add relationships

Revision ID: 156341fc3c11
Revises: 09e7d2602ecd
Create Date: 2024-01-14 06:04:08.503137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156341fc3c11'
down_revision = '09e7d2602ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
